# Make sure to edit /etc/ansible/hosts to include the right hostname for your cumulus. 
# I've add the following:
# [cumulus]
# cumulus-l-02 ansible_ssh_user=cumulus ansible_ssh_pass=password 
# Also make sure host is resolvable in DNS or /etc/hosts.
---
- hosts: cumulus-l-02
  become: yes

  tasks:
    - name: Set hostname.
      nclu:
        commands:
          - add hostname cumulus-l-02.ray.salab.local
        commit: true
    
    - name: Add VLAN's.
      nclu:
        commands:
          - add vlan 102 ip address 192.168.102.1/24
          - add vlan 104 ip address 192.168.104.1/24
          - add vlan 106 ip address 192.168.106.1/24
        commit: true
    
    - name: Add BGP router & neighbors
      nclu:
        commands:
          - add bgp autonomous-system 65002
          - add bgp neighbor 192.168.102.254 remote-as 65004
          - add bgp neighbor 192.168.104.254 remote-as 65004
          - add bgp neighbor 192.168.106.254 remote-as 65004
          - add bgp neighbor 172.16.1.1 remote-as 65000
        commit: true

    - name: Configure Route Redistribution
      nclu:
        commands:
          - add bgp redistribute connected
          - add bgp redistribute static
        commit: true